eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liguoxu/example
          username: liguoxu
          password: liguoxu1996
  application:
    name: eureka-client
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    #最大连接池数量
    maxActive: 20
    #初始化时建立物理连接的个数
    initialSize: 1
    #获取连接时最大等待时间，单位毫秒。
    maxWait: 60000
    #最小连接池数量
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql
    validationQuery: select 'x'
    #建议配置为true，不影响性能，并且保证安全性。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效
    testOnBorrow: false
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:root/code/mapper/impl/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: root.code.pojo  # 注意：对应实体类的路径
logging:
  config: classpath:config/log/logConfig.xml
server:
  port: 8888
